---
- name: Get tarball checksum
  ansible.builtin.uri:
    url: https://github.com/rancher/rke2/releases/download/{{ rke2.version }}/sha256sum-amd64.txt
    return_content: true
  register: checksums

- name: Create tempfile for tarball
  ansible.builtin.tempfile:
    state: file
  register: tarball_tempfile
  check_mode: false
  changed_when: false

- name: Download tarball
  ansible.builtin.get_url:
    url: https://github.com/rancher/rke2/releases/download/{{ rke2.version }}/rke2.linux-amd64.tar.gz
    dest: "{{ tarball_tempfile.path }}"
    mode: "0644"
    checksum: sha256:{{ checksum }}
  vars:
    checksum: "{{ checksums.content | regex_search('[0-9a-f]+ +rke2.linux-amd64.tar.gz') | regex_search('^[0-9a-f]+') }}"
  check_mode: false

- name: Extract tarball
  # ansible.builtin.unarchive:
  #     src: "{{ tarball_tempfile.path }}"
  #     dest: /usr/local
  #     remote_src: true
  ansible.builtin.shell: tar xzf "{{ tarball_tempfile.path }}" -C /usr/local
  notify: Systemd daemon reload

- name: Delete tarball
  ansible.builtin.file:
    state: absent
    path: "{{ tarball_tempfile.path }}"
