---
- name: Systemd daemon reload # noqa args[module]
  ansible.builtin.service:
    daemon_reload: true
  become: true
  listen: systemd daemon reload

- name: Restart rke2 agent service
  ansible.builtin.service:
    state: restarted
    name: rke2-agent.service
  become: true
  throttle: 1
  listen: restart rke2 agent service

- name: Restart rke2 server service
  ansible.builtin.service:
    state: restarted
    name: rke2-server.service
  become: true
  throttle: 1
  listen: restart rke2 server service

- name: Restart rke2 server service
  ansible.builtin.service:
    state: restarted
    name: systemd-sysctl
  become: true
  listen: restart sysctl
